// <auto-generated />
using System;
using DNDOnePlaceManager.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DndOnePlaceManager.Infrastructure.Migrations.MySql
{
    [DbContext(typeof(DndOneContext))]
    partial class DndOneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.ElementModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Layer")
                        .HasColumnType("int");

                    b.Property<Guid>("MapId")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Selectable")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CentralSessionId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SystemPlayerId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("UseMetric")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.MapModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GridColor")
                        .HasColumnType("longtext");

                    b.Property<int>("GridSize")
                        .HasColumnType("int");

                    b.Property<int>("GridUnitSize")
                        .HasColumnType("int");

                    b.Property<bool>("GridVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.PlayerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CentralServerUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("System")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("User")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("User");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.PropertyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ElementId");

                    b.HasIndex("GameId");

                    b.HasIndex("MapId");

                    b.HasIndex("ParentID", "Name")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.AddonModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddonModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("GameModelId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("License")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReleaseUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddonModelId");

                    b.HasIndex("GameModelId");

                    b.ToTable("Addons");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BannedUserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CentralServerUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.ActionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddonModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Hook")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddonModelId");

                    b.HasIndex("GameId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.BattleMapModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("BattleMaps");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.CardModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdditionalResources")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("AddonModelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddonModelId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool?>("FirstOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCustomUi")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsR20Card")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("MainResource")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddonModelId");

                    b.HasIndex("AddonModelId1");

                    b.HasIndex("GameId");

                    b.HasIndex("Key", "GameId")
                        .IsUnique()
                        .HasFilter("\"Key\" IS NOT NULL");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.ElementDetailModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ElementId", "Key");

                    b.ToTable("ElementsDetail");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.Chat.MessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.LayoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Default")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("GameModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameModelId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.PlaylistModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Repeat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Shuffle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.Resources.ResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddonModelId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Data")
                        .HasColumnType("longblob");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MimeType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("AddonModelId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Key", "GameId")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.Security.PermissionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("All")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModelID")
                        .HasColumnType("char(36)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerID")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ModelID");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.TreeEntryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Head")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("NewItem")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("NextId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("NextId");

                    b.HasIndex("ParentId");

                    b.ToTable("TreeEntries");
                });

            modelBuilder.Entity("PlaylistModelResourceModel", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResourcesId")
                        .HasColumnType("char(36)");

                    b.HasKey("PlaylistsId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("PlaylistModelResourceModel");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.ElementModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.MapModel", "Map")
                        .WithMany("Elements")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.MapModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Maps")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.PlayerModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.PropertyModel", b =>
                {
                    b.HasOne("DndOnePlaceManager.Domain.Entities.BattleMap.CardModel", "Card")
                        .WithMany("Properties")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.ElementModel", "Element")
                        .WithMany("Properties")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Properties")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.MapModel", "Map")
                        .WithMany("Properties")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Card");

                    b.Navigation("Element");

                    b.Navigation("Game");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.AddonModel", b =>
                {
                    b.HasOne("DndOnePlaceManager.Domain.Entities.AddonModel", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("AddonModelId");

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", null)
                        .WithMany("Addons")
                        .HasForeignKey("GameModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.ActionModel", b =>
                {
                    b.HasOne("DndOnePlaceManager.Domain.Entities.AddonModel", null)
                        .WithMany("Actions")
                        .HasForeignKey("AddonModelId");

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Actions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.BattleMapModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("BattleMaps")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.CardModel", b =>
                {
                    b.HasOne("DndOnePlaceManager.Domain.Entities.AddonModel", null)
                        .WithMany("Templates")
                        .HasForeignKey("AddonModelId");

                    b.HasOne("DndOnePlaceManager.Domain.Entities.AddonModel", null)
                        .WithMany("Views")
                        .HasForeignKey("AddonModelId1");

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Cards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.ElementDetailModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.ElementModel", "Element")
                        .WithMany("Details")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.LayoutModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Layouts")
                        .HasForeignKey("GameModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.PlaylistModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Playlists")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.Resources.ResourceModel", b =>
                {
                    b.HasOne("DndOnePlaceManager.Domain.Entities.AddonModel", null)
                        .WithMany("Resources")
                        .HasForeignKey("AddonModelId");

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("Resources")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.PlayerModel", "Player")
                        .WithMany("Resources")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.TreeEntryModel", b =>
                {
                    b.HasOne("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", "Game")
                        .WithMany("TreeEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndOnePlaceManager.Domain.Entities.TreeEntryModel", "Next")
                        .WithMany()
                        .HasForeignKey("NextId");

                    b.HasOne("DndOnePlaceManager.Domain.Entities.TreeEntryModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Game");

                    b.Navigation("Next");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PlaylistModelResourceModel", b =>
                {
                    b.HasOne("DndOnePlaceManager.Domain.Entities.PlaylistModel", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DndOnePlaceManager.Domain.Entities.Resources.ResourceModel", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.ElementModel", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.GameModel", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Addons");

                    b.Navigation("BattleMaps");

                    b.Navigation("Cards");

                    b.Navigation("Layouts");

                    b.Navigation("Maps");

                    b.Navigation("Players");

                    b.Navigation("Playlists");

                    b.Navigation("Properties");

                    b.Navigation("Resources");

                    b.Navigation("TreeEntries");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.MapModel", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("DNDOnePlaceManager.Domain.Entities.BattleMap.PlayerModel", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.AddonModel", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Dependencies");

                    b.Navigation("Resources");

                    b.Navigation("Templates");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("DndOnePlaceManager.Domain.Entities.BattleMap.CardModel", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
