<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\Actions\AddAction\" />
    <Folder Include="Commands\Addons\SwitchAddonState\" />
    <Folder Include="Commands\Auth\" />
    <Folder Include="Commands\Properties\GetProperty\" />
    <Folder Include="Commands\Properties\AddProperty\" />
    <Folder Include="Commands\Properties\RemoveProperty\" />
    <Folder Include="Commands\Properties\UpdateProperty\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>


  <ItemGroup>
    <InternalsVisibleTo Include="DNDOnePlaceManager.Application.Tests" />
    <InternalsVisibleTo Include="DndOnePlaceManager.Application.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DndOnePlaceManager.Domain\DndOnePlaceManager.Domain.csproj" />
    <ProjectReference Include="..\DndOnePlaceManager.Infrastructure\DndOnePlaceManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
